export const routeConstants = {
    ADMIN_ROOT: "/",
    SECTION_MODAL: "/admin/modal",
    SECTION_MODAL_ADD: "/admin/modal/addmodal",
    SECTION_BANNER: "/admin/homeslider",
    SECTION_BANNER_ADD: "/admin/homeslider/addhomeslider",
    CATEGORY: "/admin/category",
    SECTION_PRICING: '/admin/pricing', 
    SECTION_PRICING_ADD: "/admin/pricing/addpricing",
    SECTION_FEATURED: "/admin/featured",
    ABOUT: "/admin/about",
    ABOUT_ADD: "/admin/about/addabout",
    LOCATION: "/admin/location",
    USERS: "/admin/users",
    IMAGES: "/admin/images",
    COMMENTS: "/admin/comments",
    GALLERY: "/admin/gallery",
    ADD_CATEGORY: "/admin/addcategory",
    CONTACT: "/admin/contact",
    POSTLIMIT: "/admin/postlimit",
    PRICELIMIT: "/admin/pricelimit",
    ACCOUNT: "/admin/account",

}